source 'https://github.com/CocoaPods/Specs.git'
pod 'AWSCore'
pod 'AWSDynamoDB'
pod 'AWSS3'
pod 'AWSSNS'
pod 'AWSCognito'
pod 'UIScrollView-InfiniteScroll'
pod 'Google/Analytics'
pod 'SWTableViewCell', '~> 0.3.7'
pod 'Flurry-iOS-SDK/FlurrySDK'
pod "FBAnnotationClustering"